#include "Input.h"

FCaptureOnMousesWheelsDelegate MousesWheelsDelegate;
FCaptureOnMousesDelegate LMouseDownDelegate;
FCaptureOnMousesDelegate LMouseUpDelegate;
FCaptureOnMousesDelegate MouseDownDelegate;
FCaptureOnMousesDelegate MouseUpDelegate;
FCaptureOnMousesDelegate MouseMoveDelegate;
FCaptureOnMousesDelegate ActiveDelegate;
FCaptureOnResizeDelegate OnResetSizeDelegate;